"""Configuration globale du projet."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
INPUT_DIR = DATA_DIR / "input"
ANNOTATIONS_DIR = DATA_DIR / "annotations"
MASKS_RAW_DIR = DATA_DIR / "masks" / "raw"
MASKS_REFINED_DIR = DATA_DIR / "masks" / "refined"
OUTPUT_DIR = DATA_DIR / "output"
SEGMENTED_OBJECTS_DIR = OUTPUT_DIR / "segmented_objects"
BACKGROUND_REMOVED_DIR = OUTPUT_DIR / "background_removed"
INPAINTED_DIR = OUTPUT_DIR / "inpainted"
VISUALIZATIONS_DIR = OUTPUT_DIR / "visualizations"

MAX_IMAGE_WIDTH = 1280
MAX_IMAGE_HEIGHT = 900

GRABCUT_ITERATIONS = 5
SCRIBBLE_RADIUS = 8
RECTANGLE_COLOR = (0, 255, 255)
FOREGROUND_COLOR = (0, 255, 0)
BACKGROUND_COLOR = (255, 0, 0)
MASK_OVERLAY_ALPHA = 0.35
CONTOUR_THICKNESS = 2

MASK_OPEN_KERNEL = 3
MASK_CLOSE_KERNEL = 7
MASK_DILATE_ITERATIONS = 1
MASK_KEEP_LARGEST_COMPONENT = True
MASK_MIN_COMPONENT_AREA = 64
FEATHER_BLUR_SIZE = 11
INPAINT_MASK_DILATION = 2

# Phase finale segmentation
ROI_MARGIN_RATIO = 0.25
CENTER_PRIOR_MARGIN_RATIO = 0.12
GRABCUT_GAUSSIAN_BLUR = 3

# Inpainting
INPAINT_ROI_MARGIN_RATIO = 0.20
INPAINT_MIN_ROI_PADDING = 24
INPAINT_FEATHER_BLUR_SIZE = 17
INPAINT_FALLBACK_RADIUS = 3
INPAINT_FALLBACK_METHOD = "telea"  # telea | ns
INPAINT_DEBUG_LOG = True
UI_BUTTON_HEIGHT = 36
